// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using form_API.Data;

#nullable disable

namespace form_API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260521202457_AddJwtAuthUsuariosDiretoria")]
    partial class AddJwtAuthUsuariosDiretoria
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("form_API.Models.Aluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DataNasc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProfessorId")
                        .HasColumnType("int");

                    b.Property<string>("Sobrenome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdUsuario");

                    b.HasIndex("ProfessorId");

                    b.ToTable("Alunos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataNasc = "25/02/1982",
                            IdUsuario = 12,
                            Nome = "Maria",
                            ProfessorId = 1,
                            Sobrenome = "Solano"
                        },
                        new
                        {
                            Id = 2,
                            DataNasc = "25/01/2000",
                            IdUsuario = 13,
                            Nome = "Joao",
                            ProfessorId = 2,
                            Sobrenome = "Gomes"
                        },
                        new
                        {
                            Id = 3,
                            DataNasc = "22/02/2002",
                            IdUsuario = 14,
                            Nome = "Alex",
                            ProfessorId = 3,
                            Sobrenome = "Alves"
                        },
                        new
                        {
                            Id = 4,
                            DataNasc = "04/04/1983",
                            IdUsuario = 15,
                            Nome = "Ana",
                            ProfessorId = 4,
                            Sobrenome = "Silva"
                        },
                        new
                        {
                            Id = 5,
                            DataNasc = "05/05/1984",
                            IdUsuario = 16,
                            Nome = "Bruno",
                            ProfessorId = 5,
                            Sobrenome = "Santos"
                        },
                        new
                        {
                            Id = 6,
                            DataNasc = "06/06/1985",
                            IdUsuario = 17,
                            Nome = "Carla",
                            ProfessorId = 6,
                            Sobrenome = "Oliveira"
                        },
                        new
                        {
                            Id = 7,
                            DataNasc = "07/07/1986",
                            IdUsuario = 18,
                            Nome = "Daniel",
                            ProfessorId = 7,
                            Sobrenome = "Souza"
                        },
                        new
                        {
                            Id = 8,
                            DataNasc = "08/08/1987",
                            IdUsuario = 19,
                            Nome = "Elisa",
                            ProfessorId = 8,
                            Sobrenome = "Pereira"
                        },
                        new
                        {
                            Id = 9,
                            DataNasc = "09/09/1988",
                            IdUsuario = 20,
                            Nome = "Fabio",
                            ProfessorId = 9,
                            Sobrenome = "Costa"
                        },
                        new
                        {
                            Id = 10,
                            DataNasc = "10/10/1989",
                            Nome = "Gabriela",
                            ProfessorId = 10,
                            Sobrenome = "Rodrigues"
                        },
                        new
                        {
                            Id = 11,
                            DataNasc = "11/11/1990",
                            Nome = "Hugo",
                            ProfessorId = 11,
                            Sobrenome = "Almeida"
                        },
                        new
                        {
                            Id = 12,
                            DataNasc = "12/12/1991",
                            Nome = "Isabela",
                            ProfessorId = 12,
                            Sobrenome = "Nascimento"
                        },
                        new
                        {
                            Id = 13,
                            DataNasc = "13/01/1992",
                            Nome = "Jonas",
                            ProfessorId = 13,
                            Sobrenome = "Lima"
                        },
                        new
                        {
                            Id = 14,
                            DataNasc = "14/02/1993",
                            Nome = "Karina",
                            ProfessorId = 14,
                            Sobrenome = "Araujo"
                        },
                        new
                        {
                            Id = 15,
                            DataNasc = "15/03/1994",
                            Nome = "Luis",
                            ProfessorId = 15,
                            Sobrenome = "Ferreira"
                        },
                        new
                        {
                            Id = 16,
                            DataNasc = "16/04/1995",
                            Nome = "Manuela",
                            ProfessorId = 16,
                            Sobrenome = "Carvalho"
                        },
                        new
                        {
                            Id = 17,
                            DataNasc = "17/05/1996",
                            Nome = "Nicolas",
                            ProfessorId = 17,
                            Sobrenome = "Ribeiro"
                        },
                        new
                        {
                            Id = 18,
                            DataNasc = "18/06/1997",
                            Nome = "Olivia",
                            ProfessorId = 18,
                            Sobrenome = "Martins"
                        },
                        new
                        {
                            Id = 19,
                            DataNasc = "19/07/1998",
                            Nome = "Pedro",
                            ProfessorId = 19,
                            Sobrenome = "Rocha"
                        },
                        new
                        {
                            Id = 20,
                            DataNasc = "20/08/1999",
                            Nome = "Rafaela",
                            ProfessorId = 20,
                            Sobrenome = "Barbosa"
                        },
                        new
                        {
                            Id = 21,
                            DataNasc = "21/09/2000",
                            Nome = "Sofia",
                            ProfessorId = 21,
                            Sobrenome = "Dias"
                        },
                        new
                        {
                            Id = 22,
                            DataNasc = "22/10/2001",
                            Nome = "Tiago",
                            ProfessorId = 22,
                            Sobrenome = "Teixeira"
                        },
                        new
                        {
                            Id = 23,
                            DataNasc = "23/11/2002",
                            Nome = "Ursula",
                            ProfessorId = 23,
                            Sobrenome = "Correia"
                        },
                        new
                        {
                            Id = 24,
                            DataNasc = "24/12/2003",
                            Nome = "Victor",
                            ProfessorId = 24,
                            Sobrenome = "Mendes"
                        },
                        new
                        {
                            Id = 25,
                            DataNasc = "25/01/2004",
                            Nome = "Wesley",
                            ProfessorId = 25,
                            Sobrenome = "Cardoso"
                        },
                        new
                        {
                            Id = 26,
                            DataNasc = "26/02/1980",
                            Nome = "Yasmin",
                            ProfessorId = 26,
                            Sobrenome = "Ramos"
                        },
                        new
                        {
                            Id = 27,
                            DataNasc = "27/03/1981",
                            Nome = "Zoe",
                            ProfessorId = 27,
                            Sobrenome = "Castro"
                        },
                        new
                        {
                            Id = 28,
                            DataNasc = "28/04/1982",
                            Nome = "Arthur",
                            ProfessorId = 28,
                            Sobrenome = "Fernandes"
                        },
                        new
                        {
                            Id = 29,
                            DataNasc = "01/05/1983",
                            Nome = "Bianca",
                            ProfessorId = 29,
                            Sobrenome = "Moreira"
                        },
                        new
                        {
                            Id = 30,
                            DataNasc = "02/06/1984",
                            Nome = "Caio",
                            ProfessorId = 30,
                            Sobrenome = "Moura"
                        },
                        new
                        {
                            Id = 31,
                            DataNasc = "03/07/1985",
                            Nome = "Debora",
                            ProfessorId = 31,
                            Sobrenome = "Batista"
                        },
                        new
                        {
                            Id = 32,
                            DataNasc = "04/08/1986",
                            Nome = "Enzo",
                            ProfessorId = 32,
                            Sobrenome = "Freitas"
                        },
                        new
                        {
                            Id = 33,
                            DataNasc = "05/09/1987",
                            Nome = "Flavia",
                            ProfessorId = 33,
                            Sobrenome = "Monteiro"
                        },
                        new
                        {
                            Id = 34,
                            DataNasc = "06/10/1988",
                            Nome = "Guilherme",
                            ProfessorId = 34,
                            Sobrenome = "Campos"
                        },
                        new
                        {
                            Id = 35,
                            DataNasc = "07/11/1989",
                            Nome = "Helena",
                            ProfessorId = 35,
                            Sobrenome = "Vieira"
                        },
                        new
                        {
                            Id = 36,
                            DataNasc = "08/12/1990",
                            Nome = "Igor",
                            ProfessorId = 36,
                            Sobrenome = "Pinto"
                        },
                        new
                        {
                            Id = 37,
                            DataNasc = "09/01/1991",
                            Nome = "Julia",
                            ProfessorId = 37,
                            Sobrenome = "Cavalcanti"
                        },
                        new
                        {
                            Id = 38,
                            DataNasc = "10/02/1992",
                            Nome = "Kevin",
                            ProfessorId = 38,
                            Sobrenome = "Farias"
                        },
                        new
                        {
                            Id = 39,
                            DataNasc = "11/03/1993",
                            Nome = "Laura",
                            ProfessorId = 39,
                            Sobrenome = "Cunha"
                        },
                        new
                        {
                            Id = 40,
                            DataNasc = "12/04/1994",
                            Nome = "Miguel",
                            ProfessorId = 40,
                            Sobrenome = "Duarte"
                        },
                        new
                        {
                            Id = 41,
                            DataNasc = "13/05/1995",
                            Nome = "Natalia",
                            ProfessorId = 41,
                            Sobrenome = "Lopes"
                        },
                        new
                        {
                            Id = 42,
                            DataNasc = "14/06/1996",
                            Nome = "Otavio",
                            ProfessorId = 42,
                            Sobrenome = "Reis"
                        },
                        new
                        {
                            Id = 43,
                            DataNasc = "15/07/1997",
                            Nome = "Pamela",
                            ProfessorId = 43,
                            Sobrenome = "Pires"
                        },
                        new
                        {
                            Id = 44,
                            DataNasc = "16/08/1998",
                            Nome = "Rafael",
                            ProfessorId = 44,
                            Sobrenome = "Tavares"
                        },
                        new
                        {
                            Id = 45,
                            DataNasc = "17/09/1999",
                            Nome = "Sabrina",
                            ProfessorId = 45,
                            Sobrenome = "Mello"
                        },
                        new
                        {
                            Id = 46,
                            DataNasc = "18/10/2000",
                            Nome = "Tales",
                            ProfessorId = 46,
                            Sobrenome = "Assis"
                        },
                        new
                        {
                            Id = 47,
                            DataNasc = "19/11/2001",
                            Nome = "Vanessa",
                            ProfessorId = 47,
                            Sobrenome = "Peixoto"
                        },
                        new
                        {
                            Id = 48,
                            DataNasc = "20/12/2002",
                            Nome = "William",
                            ProfessorId = 48,
                            Sobrenome = "Nunes"
                        },
                        new
                        {
                            Id = 49,
                            DataNasc = "21/01/2003",
                            Nome = "Xenia",
                            ProfessorId = 49,
                            Sobrenome = "Macedo"
                        },
                        new
                        {
                            Id = 50,
                            DataNasc = "22/02/2004",
                            Nome = "Yuri",
                            ProfessorId = 50,
                            Sobrenome = "Brito"
                        });
                });

            modelBuilder.Entity("form_API.Models.Diretoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Diretoria", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IdUsuario = 1,
                            Nome = "Administrador Sistema"
                        });
                });

            modelBuilder.Entity("form_API.Models.Perfil", b =>
                {
                    b.Property<int>("IdPerfil")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPerfil"));

                    b.Property<string>("DescricaoPerfil")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdPerfil");

                    b.ToTable("Perfil", (string)null);

                    b.HasData(
                        new
                        {
                            IdPerfil = 1,
                            DescricaoPerfil = "Administrador"
                        },
                        new
                        {
                            IdPerfil = 2,
                            DescricaoPerfil = "Contribuinte"
                        },
                        new
                        {
                            IdPerfil = 3,
                            DescricaoPerfil = "Leitor"
                        });
                });

            modelBuilder.Entity("form_API.Models.Professor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Professores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IdUsuario = 2,
                            Nome = "Vinicius"
                        },
                        new
                        {
                            Id = 2,
                            IdUsuario = 3,
                            Nome = "Paula"
                        },
                        new
                        {
                            Id = 3,
                            IdUsuario = 4,
                            Nome = "Suzana"
                        },
                        new
                        {
                            Id = 4,
                            IdUsuario = 5,
                            Nome = "Carlos"
                        },
                        new
                        {
                            Id = 5,
                            IdUsuario = 6,
                            Nome = "Mariana"
                        },
                        new
                        {
                            Id = 6,
                            IdUsuario = 7,
                            Nome = "Roberto"
                        },
                        new
                        {
                            Id = 7,
                            IdUsuario = 8,
                            Nome = "Fernanda"
                        },
                        new
                        {
                            Id = 8,
                            IdUsuario = 9,
                            Nome = "Ricardo"
                        },
                        new
                        {
                            Id = 9,
                            IdUsuario = 10,
                            Nome = "Patricia"
                        },
                        new
                        {
                            Id = 10,
                            IdUsuario = 11,
                            Nome = "Marcelo"
                        },
                        new
                        {
                            Id = 11,
                            Nome = "Aline"
                        },
                        new
                        {
                            Id = 12,
                            Nome = "Eduardo"
                        },
                        new
                        {
                            Id = 13,
                            Nome = "Juliana"
                        },
                        new
                        {
                            Id = 14,
                            Nome = "Renato"
                        },
                        new
                        {
                            Id = 15,
                            Nome = "Camila"
                        },
                        new
                        {
                            Id = 16,
                            Nome = "Gustavo"
                        },
                        new
                        {
                            Id = 17,
                            Nome = "Beatriz"
                        },
                        new
                        {
                            Id = 18,
                            Nome = "Felipe"
                        },
                        new
                        {
                            Id = 19,
                            Nome = "Larissa"
                        },
                        new
                        {
                            Id = 20,
                            Nome = "Diego"
                        },
                        new
                        {
                            Id = 21,
                            Nome = "Tatiane"
                        },
                        new
                        {
                            Id = 22,
                            Nome = "Rafael"
                        },
                        new
                        {
                            Id = 23,
                            Nome = "Carolina"
                        },
                        new
                        {
                            Id = 24,
                            Nome = "Henrique"
                        },
                        new
                        {
                            Id = 25,
                            Nome = "Vanessa"
                        },
                        new
                        {
                            Id = 26,
                            Nome = "Leonardo"
                        },
                        new
                        {
                            Id = 27,
                            Nome = "Priscila"
                        },
                        new
                        {
                            Id = 28,
                            Nome = "Andre"
                        },
                        new
                        {
                            Id = 29,
                            Nome = "Simone"
                        },
                        new
                        {
                            Id = 30,
                            Nome = "Thiago"
                        },
                        new
                        {
                            Id = 31,
                            Nome = "Monica"
                        },
                        new
                        {
                            Id = 32,
                            Nome = "Fabio"
                        },
                        new
                        {
                            Id = 33,
                            Nome = "Daniela"
                        },
                        new
                        {
                            Id = 34,
                            Nome = "Rodrigo"
                        },
                        new
                        {
                            Id = 35,
                            Nome = "Leticia"
                        },
                        new
                        {
                            Id = 36,
                            Nome = "Sergio"
                        },
                        new
                        {
                            Id = 37,
                            Nome = "Bruna"
                        },
                        new
                        {
                            Id = 38,
                            Nome = "Caio"
                        },
                        new
                        {
                            Id = 39,
                            Nome = "Gabriela"
                        },
                        new
                        {
                            Id = 40,
                            Nome = "Samuel"
                        },
                        new
                        {
                            Id = 41,
                            Nome = "Isabela"
                        },
                        new
                        {
                            Id = 42,
                            Nome = "Lucas"
                        },
                        new
                        {
                            Id = 43,
                            Nome = "Natalia"
                        },
                        new
                        {
                            Id = 44,
                            Nome = "Paulo"
                        },
                        new
                        {
                            Id = 45,
                            Nome = "Bianca"
                        },
                        new
                        {
                            Id = 46,
                            Nome = "Matheus"
                        },
                        new
                        {
                            Id = 47,
                            Nome = "Renata"
                        },
                        new
                        {
                            Id = 48,
                            Nome = "Vitor"
                        },
                        new
                        {
                            Id = 49,
                            Nome = "Amanda"
                        },
                        new
                        {
                            Id = 50,
                            Nome = "Leandro"
                        });
                });

            modelBuilder.Entity("form_API.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("IdPerfil")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdUsuario");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IdPerfil");

                    b.ToTable("Usuario", (string)null);

                    b.HasData(
                        new
                        {
                            IdUsuario = 1,
                            Email = "admin@escola.com",
                            IdPerfil = 1,
                            Nome = "Administrador Sistema",
                            Senha = "PBKDF2-SHA256$100000$dXN1YXJpby1zZWVkLTAx$FfQ5HKxd+P+bqyIRbLEJT21eK0xwqw0fRymSJ50btiM=",
                            Telefone = "11999990001"
                        },
                        new
                        {
                            IdUsuario = 2,
                            Email = "professor01@escola.com",
                            IdPerfil = 2,
                            Nome = "Professor Vinicius",
                            Senha = "PBKDF2-SHA256$100000$dXN1YXJpby1zZWVkLTAy$LzErqoJ36wdajqImPtWmjfIDcSHdw/Qsd0yPTJDXANA=",
                            Telefone = "11988880001"
                        },
                        new
                        {
                            IdUsuario = 3,
                            Email = "professor02@escola.com",
                            IdPerfil = 2,
                            Nome = "Professor Paula",
                            Senha = "PBKDF2-SHA256$100000$dXN1YXJpby1zZWVkLTAz$2ZjPXI5OMTXvvZcLsCWjvzrPiZjbJM4UUispcmKV2pE=",
                            Telefone = "11988880002"
                        },
                        new
                        {
                            IdUsuario = 4,
                            Email = "professor03@escola.com",
                            IdPerfil = 2,
                            Nome = "Professor Suzana",
                            Senha = "PBKDF2-SHA256$100000$dXN1YXJpby1zZWVkLTA0$me64hINFuBY2VgrYnV00Rt9o4O3DcKOF6ERXELwK4oo=",
                            Telefone = "11988880003"
                        },
                        new
                        {
                            IdUsuario = 5,
                            Email = "professor04@escola.com",
                            IdPerfil = 2,
                            Nome = "Professor Carlos",
                            Senha = "PBKDF2-SHA256$100000$dXN1YXJpby1zZWVkLTA1$BeQmoNfbZekUVMDeCs0DshesPlX/lWejxwjbOomV+SQ=",
                            Telefone = "11988880004"
                        },
                        new
                        {
                            IdUsuario = 6,
                            Email = "professor05@escola.com",
                            IdPerfil = 2,
                            Nome = "Professor Mariana",
                            Senha = "PBKDF2-SHA256$100000$dXN1YXJpby1zZWVkLTA2$VLz/eGnLJgRIP2hrbQiYK6iAL4AJHl+PUEe15qKAyu0=",
                            Telefone = "11988880005"
                        },
                        new
                        {
                            IdUsuario = 7,
                            Email = "professor06@escola.com",
                            IdPerfil = 2,
                            Nome = "Professor Roberto",
                            Senha = "PBKDF2-SHA256$100000$dXN1YXJpby1zZWVkLTA3$r52DPiT2e9YLVzIVcB6GkIH8LLA2WYqjl+JDK3VV96w=",
                            Telefone = "11988880006"
                        },
                        new
                        {
                            IdUsuario = 8,
                            Email = "professor07@escola.com",
                            IdPerfil = 2,
                            Nome = "Professor Fernanda",
                            Senha = "PBKDF2-SHA256$100000$dXN1YXJpby1zZWVkLTA4$xNGwJEi2R8Zc+ERPBwp4xsrb3UgrcTWrXu5Ro68EzRw=",
                            Telefone = "11988880007"
                        },
                        new
                        {
                            IdUsuario = 9,
                            Email = "professor08@escola.com",
                            IdPerfil = 2,
                            Nome = "Professor Ricardo",
                            Senha = "PBKDF2-SHA256$100000$dXN1YXJpby1zZWVkLTA5$WqNwjDfux46SoJFVp8URb25WqhvfnnqSSezf4mTHmO0=",
                            Telefone = "11988880008"
                        },
                        new
                        {
                            IdUsuario = 10,
                            Email = "professor09@escola.com",
                            IdPerfil = 2,
                            Nome = "Professor Patricia",
                            Senha = "PBKDF2-SHA256$100000$dXN1YXJpby1zZWVkLTEw$8pck4mOGxTBDGJ7TuNhF4fIvWVP1BukeZeSMOI9EovA=",
                            Telefone = "11988880009"
                        },
                        new
                        {
                            IdUsuario = 11,
                            Email = "professor10@escola.com",
                            IdPerfil = 2,
                            Nome = "Professor Marcelo",
                            Senha = "PBKDF2-SHA256$100000$dXN1YXJpby1zZWVkLTEx$pGtYaxggmZZrorWXNTVbhtpFw9qWgDXDj8LZlaKTRyw=",
                            Telefone = "11988880010"
                        },
                        new
                        {
                            IdUsuario = 12,
                            Email = "aluno01@escola.com",
                            IdPerfil = 3,
                            Nome = "Aluno Maria",
                            Senha = "PBKDF2-SHA256$100000$dXN1YXJpby1zZWVkLTEy$PSoiqNNWzRiAvRVzute150mhDSL4rTOTisKBi9TTrJM=",
                            Telefone = "11977770001"
                        },
                        new
                        {
                            IdUsuario = 13,
                            Email = "aluno02@escola.com",
                            IdPerfil = 3,
                            Nome = "Aluno Joao",
                            Senha = "PBKDF2-SHA256$100000$dXN1YXJpby1zZWVkLTEz$sxGpNfM7WC8nMjkLmcQ9WN2J6Lhe7O07oyFXwLO4/iU=",
                            Telefone = "11977770002"
                        },
                        new
                        {
                            IdUsuario = 14,
                            Email = "aluno03@escola.com",
                            IdPerfil = 3,
                            Nome = "Aluno Alex",
                            Senha = "PBKDF2-SHA256$100000$dXN1YXJpby1zZWVkLTE0$0mh8FyroAgQNjTYZXcypWMYARFKyzXJ48MNVyB78E+U=",
                            Telefone = "11977770003"
                        },
                        new
                        {
                            IdUsuario = 15,
                            Email = "aluno04@escola.com",
                            IdPerfil = 3,
                            Nome = "Aluno Ana",
                            Senha = "PBKDF2-SHA256$100000$dXN1YXJpby1zZWVkLTE1$SpupVdnneUNyvnPwlmVBvm0OUOr/Yjov1o5xA20Q1+w=",
                            Telefone = "11977770004"
                        },
                        new
                        {
                            IdUsuario = 16,
                            Email = "aluno05@escola.com",
                            IdPerfil = 3,
                            Nome = "Aluno Bruno",
                            Senha = "PBKDF2-SHA256$100000$dXN1YXJpby1zZWVkLTE2$oqDVRdKBe7SS3kMj3hAd6kgoC9dH9f8fyOHlTOZrl9k=",
                            Telefone = "11977770005"
                        },
                        new
                        {
                            IdUsuario = 17,
                            Email = "aluno06@escola.com",
                            IdPerfil = 3,
                            Nome = "Aluno Carla",
                            Senha = "PBKDF2-SHA256$100000$dXN1YXJpby1zZWVkLTE3$ss/qC9hAEFzI4JwGoPvKuAuI4DN8bXtKp1Ulbt/WF1o=",
                            Telefone = "11977770006"
                        },
                        new
                        {
                            IdUsuario = 18,
                            Email = "aluno07@escola.com",
                            IdPerfil = 3,
                            Nome = "Aluno Daniel",
                            Senha = "PBKDF2-SHA256$100000$dXN1YXJpby1zZWVkLTE4$Ks5ex2/VDVyP7B3EbbqTJqr/34e1PGXqDCTx30kSYdk=",
                            Telefone = "11977770007"
                        },
                        new
                        {
                            IdUsuario = 19,
                            Email = "aluno08@escola.com",
                            IdPerfil = 3,
                            Nome = "Aluno Elisa",
                            Senha = "PBKDF2-SHA256$100000$dXN1YXJpby1zZWVkLTE5$p4DpMKEz6wYRtFN4Qimq7IhXnIl+So6O8D7Zl82D59M=",
                            Telefone = "11977770008"
                        },
                        new
                        {
                            IdUsuario = 20,
                            Email = "aluno09@escola.com",
                            IdPerfil = 3,
                            Nome = "Aluno Fabio",
                            Senha = "PBKDF2-SHA256$100000$dXN1YXJpby1zZWVkLTIw$XIIyE2s98F4W58nJ2sbRe5rriyLwskk2/VxBAgNNSZc=",
                            Telefone = "11977770009"
                        });
                });

            modelBuilder.Entity("form_API.Models.Aluno", b =>
                {
                    b.HasOne("form_API.Models.Usuario", "Usuario")
                        .WithMany("Alunos")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("form_API.Models.Professor", "Professor")
                        .WithMany("Alunos")
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Professor");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("form_API.Models.Diretoria", b =>
                {
                    b.HasOne("form_API.Models.Usuario", "Usuario")
                        .WithMany("Diretorias")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("form_API.Models.Professor", b =>
                {
                    b.HasOne("form_API.Models.Usuario", "Usuario")
                        .WithMany("Professores")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("form_API.Models.Usuario", b =>
                {
                    b.HasOne("form_API.Models.Perfil", "Perfil")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdPerfil")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("form_API.Models.Perfil", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("form_API.Models.Professor", b =>
                {
                    b.Navigation("Alunos");
                });

            modelBuilder.Entity("form_API.Models.Usuario", b =>
                {
                    b.Navigation("Alunos");

                    b.Navigation("Diretorias");

                    b.Navigation("Professores");
                });
#pragma warning restore 612, 618
        }
    }
}
