// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using form_API.Data;

#nullable disable

namespace form_API.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("form_API.Models.Aluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DataNasc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProfessorId")
                        .HasColumnType("int");

                    b.Property<string>("Sobrenome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProfessorId");

                    b.ToTable("Alunos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataNasc = "25/02/1982",
                            Nome = "Maria",
                            ProfessorId = 1,
                            Sobrenome = "Solano"
                        },
                        new
                        {
                            Id = 2,
                            DataNasc = "25/01/2000",
                            Nome = "Joao",
                            ProfessorId = 2,
                            Sobrenome = "Gomes"
                        },
                        new
                        {
                            Id = 3,
                            DataNasc = "22/02/2002",
                            Nome = "Alex",
                            ProfessorId = 3,
                            Sobrenome = "Alves"
                        },
                        new
                        {
                            Id = 4,
                            DataNasc = "04/04/1983",
                            Nome = "Ana",
                            ProfessorId = 4,
                            Sobrenome = "Silva"
                        },
                        new
                        {
                            Id = 5,
                            DataNasc = "05/05/1984",
                            Nome = "Bruno",
                            ProfessorId = 5,
                            Sobrenome = "Santos"
                        },
                        new
                        {
                            Id = 6,
                            DataNasc = "06/06/1985",
                            Nome = "Carla",
                            ProfessorId = 6,
                            Sobrenome = "Oliveira"
                        },
                        new
                        {
                            Id = 7,
                            DataNasc = "07/07/1986",
                            Nome = "Daniel",
                            ProfessorId = 7,
                            Sobrenome = "Souza"
                        },
                        new
                        {
                            Id = 8,
                            DataNasc = "08/08/1987",
                            Nome = "Elisa",
                            ProfessorId = 8,
                            Sobrenome = "Pereira"
                        },
                        new
                        {
                            Id = 9,
                            DataNasc = "09/09/1988",
                            Nome = "Fabio",
                            ProfessorId = 9,
                            Sobrenome = "Costa"
                        },
                        new
                        {
                            Id = 10,
                            DataNasc = "10/10/1989",
                            Nome = "Gabriela",
                            ProfessorId = 10,
                            Sobrenome = "Rodrigues"
                        },
                        new
                        {
                            Id = 11,
                            DataNasc = "11/11/1990",
                            Nome = "Hugo",
                            ProfessorId = 11,
                            Sobrenome = "Almeida"
                        },
                        new
                        {
                            Id = 12,
                            DataNasc = "12/12/1991",
                            Nome = "Isabela",
                            ProfessorId = 12,
                            Sobrenome = "Nascimento"
                        },
                        new
                        {
                            Id = 13,
                            DataNasc = "13/01/1992",
                            Nome = "Jonas",
                            ProfessorId = 13,
                            Sobrenome = "Lima"
                        },
                        new
                        {
                            Id = 14,
                            DataNasc = "14/02/1993",
                            Nome = "Karina",
                            ProfessorId = 14,
                            Sobrenome = "Araujo"
                        },
                        new
                        {
                            Id = 15,
                            DataNasc = "15/03/1994",
                            Nome = "Luis",
                            ProfessorId = 15,
                            Sobrenome = "Ferreira"
                        },
                        new
                        {
                            Id = 16,
                            DataNasc = "16/04/1995",
                            Nome = "Manuela",
                            ProfessorId = 16,
                            Sobrenome = "Carvalho"
                        },
                        new
                        {
                            Id = 17,
                            DataNasc = "17/05/1996",
                            Nome = "Nicolas",
                            ProfessorId = 17,
                            Sobrenome = "Ribeiro"
                        },
                        new
                        {
                            Id = 18,
                            DataNasc = "18/06/1997",
                            Nome = "Olivia",
                            ProfessorId = 18,
                            Sobrenome = "Martins"
                        },
                        new
                        {
                            Id = 19,
                            DataNasc = "19/07/1998",
                            Nome = "Pedro",
                            ProfessorId = 19,
                            Sobrenome = "Rocha"
                        },
                        new
                        {
                            Id = 20,
                            DataNasc = "20/08/1999",
                            Nome = "Rafaela",
                            ProfessorId = 20,
                            Sobrenome = "Barbosa"
                        },
                        new
                        {
                            Id = 21,
                            DataNasc = "21/09/2000",
                            Nome = "Sofia",
                            ProfessorId = 21,
                            Sobrenome = "Dias"
                        },
                        new
                        {
                            Id = 22,
                            DataNasc = "22/10/2001",
                            Nome = "Tiago",
                            ProfessorId = 22,
                            Sobrenome = "Teixeira"
                        },
                        new
                        {
                            Id = 23,
                            DataNasc = "23/11/2002",
                            Nome = "Ursula",
                            ProfessorId = 23,
                            Sobrenome = "Correia"
                        },
                        new
                        {
                            Id = 24,
                            DataNasc = "24/12/2003",
                            Nome = "Victor",
                            ProfessorId = 24,
                            Sobrenome = "Mendes"
                        },
                        new
                        {
                            Id = 25,
                            DataNasc = "25/01/2004",
                            Nome = "Wesley",
                            ProfessorId = 25,
                            Sobrenome = "Cardoso"
                        },
                        new
                        {
                            Id = 26,
                            DataNasc = "26/02/1980",
                            Nome = "Yasmin",
                            ProfessorId = 26,
                            Sobrenome = "Ramos"
                        },
                        new
                        {
                            Id = 27,
                            DataNasc = "27/03/1981",
                            Nome = "Zoe",
                            ProfessorId = 27,
                            Sobrenome = "Castro"
                        },
                        new
                        {
                            Id = 28,
                            DataNasc = "28/04/1982",
                            Nome = "Arthur",
                            ProfessorId = 28,
                            Sobrenome = "Fernandes"
                        },
                        new
                        {
                            Id = 29,
                            DataNasc = "01/05/1983",
                            Nome = "Bianca",
                            ProfessorId = 29,
                            Sobrenome = "Moreira"
                        },
                        new
                        {
                            Id = 30,
                            DataNasc = "02/06/1984",
                            Nome = "Caio",
                            ProfessorId = 30,
                            Sobrenome = "Moura"
                        },
                        new
                        {
                            Id = 31,
                            DataNasc = "03/07/1985",
                            Nome = "Debora",
                            ProfessorId = 31,
                            Sobrenome = "Batista"
                        },
                        new
                        {
                            Id = 32,
                            DataNasc = "04/08/1986",
                            Nome = "Enzo",
                            ProfessorId = 32,
                            Sobrenome = "Freitas"
                        },
                        new
                        {
                            Id = 33,
                            DataNasc = "05/09/1987",
                            Nome = "Flavia",
                            ProfessorId = 33,
                            Sobrenome = "Monteiro"
                        },
                        new
                        {
                            Id = 34,
                            DataNasc = "06/10/1988",
                            Nome = "Guilherme",
                            ProfessorId = 34,
                            Sobrenome = "Campos"
                        },
                        new
                        {
                            Id = 35,
                            DataNasc = "07/11/1989",
                            Nome = "Helena",
                            ProfessorId = 35,
                            Sobrenome = "Vieira"
                        },
                        new
                        {
                            Id = 36,
                            DataNasc = "08/12/1990",
                            Nome = "Igor",
                            ProfessorId = 36,
                            Sobrenome = "Pinto"
                        },
                        new
                        {
                            Id = 37,
                            DataNasc = "09/01/1991",
                            Nome = "Julia",
                            ProfessorId = 37,
                            Sobrenome = "Cavalcanti"
                        },
                        new
                        {
                            Id = 38,
                            DataNasc = "10/02/1992",
                            Nome = "Kevin",
                            ProfessorId = 38,
                            Sobrenome = "Farias"
                        },
                        new
                        {
                            Id = 39,
                            DataNasc = "11/03/1993",
                            Nome = "Laura",
                            ProfessorId = 39,
                            Sobrenome = "Cunha"
                        },
                        new
                        {
                            Id = 40,
                            DataNasc = "12/04/1994",
                            Nome = "Miguel",
                            ProfessorId = 40,
                            Sobrenome = "Duarte"
                        },
                        new
                        {
                            Id = 41,
                            DataNasc = "13/05/1995",
                            Nome = "Natalia",
                            ProfessorId = 41,
                            Sobrenome = "Lopes"
                        },
                        new
                        {
                            Id = 42,
                            DataNasc = "14/06/1996",
                            Nome = "Otavio",
                            ProfessorId = 42,
                            Sobrenome = "Reis"
                        },
                        new
                        {
                            Id = 43,
                            DataNasc = "15/07/1997",
                            Nome = "Pamela",
                            ProfessorId = 43,
                            Sobrenome = "Pires"
                        },
                        new
                        {
                            Id = 44,
                            DataNasc = "16/08/1998",
                            Nome = "Rafael",
                            ProfessorId = 44,
                            Sobrenome = "Tavares"
                        },
                        new
                        {
                            Id = 45,
                            DataNasc = "17/09/1999",
                            Nome = "Sabrina",
                            ProfessorId = 45,
                            Sobrenome = "Mello"
                        },
                        new
                        {
                            Id = 46,
                            DataNasc = "18/10/2000",
                            Nome = "Tales",
                            ProfessorId = 46,
                            Sobrenome = "Assis"
                        },
                        new
                        {
                            Id = 47,
                            DataNasc = "19/11/2001",
                            Nome = "Vanessa",
                            ProfessorId = 47,
                            Sobrenome = "Peixoto"
                        },
                        new
                        {
                            Id = 48,
                            DataNasc = "20/12/2002",
                            Nome = "William",
                            ProfessorId = 48,
                            Sobrenome = "Nunes"
                        },
                        new
                        {
                            Id = 49,
                            DataNasc = "21/01/2003",
                            Nome = "Xenia",
                            ProfessorId = 49,
                            Sobrenome = "Macedo"
                        },
                        new
                        {
                            Id = 50,
                            DataNasc = "22/02/2004",
                            Nome = "Yuri",
                            ProfessorId = 50,
                            Sobrenome = "Brito"
                        });
                });

            modelBuilder.Entity("form_API.Models.Professor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Professores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Vinicius"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Paula"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Suzana"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Carlos"
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Mariana"
                        },
                        new
                        {
                            Id = 6,
                            Nome = "Roberto"
                        },
                        new
                        {
                            Id = 7,
                            Nome = "Fernanda"
                        },
                        new
                        {
                            Id = 8,
                            Nome = "Ricardo"
                        },
                        new
                        {
                            Id = 9,
                            Nome = "Patricia"
                        },
                        new
                        {
                            Id = 10,
                            Nome = "Marcelo"
                        },
                        new
                        {
                            Id = 11,
                            Nome = "Aline"
                        },
                        new
                        {
                            Id = 12,
                            Nome = "Eduardo"
                        },
                        new
                        {
                            Id = 13,
                            Nome = "Juliana"
                        },
                        new
                        {
                            Id = 14,
                            Nome = "Renato"
                        },
                        new
                        {
                            Id = 15,
                            Nome = "Camila"
                        },
                        new
                        {
                            Id = 16,
                            Nome = "Gustavo"
                        },
                        new
                        {
                            Id = 17,
                            Nome = "Beatriz"
                        },
                        new
                        {
                            Id = 18,
                            Nome = "Felipe"
                        },
                        new
                        {
                            Id = 19,
                            Nome = "Larissa"
                        },
                        new
                        {
                            Id = 20,
                            Nome = "Diego"
                        },
                        new
                        {
                            Id = 21,
                            Nome = "Tatiane"
                        },
                        new
                        {
                            Id = 22,
                            Nome = "Rafael"
                        },
                        new
                        {
                            Id = 23,
                            Nome = "Carolina"
                        },
                        new
                        {
                            Id = 24,
                            Nome = "Henrique"
                        },
                        new
                        {
                            Id = 25,
                            Nome = "Vanessa"
                        },
                        new
                        {
                            Id = 26,
                            Nome = "Leonardo"
                        },
                        new
                        {
                            Id = 27,
                            Nome = "Priscila"
                        },
                        new
                        {
                            Id = 28,
                            Nome = "Andre"
                        },
                        new
                        {
                            Id = 29,
                            Nome = "Simone"
                        },
                        new
                        {
                            Id = 30,
                            Nome = "Thiago"
                        },
                        new
                        {
                            Id = 31,
                            Nome = "Monica"
                        },
                        new
                        {
                            Id = 32,
                            Nome = "Fabio"
                        },
                        new
                        {
                            Id = 33,
                            Nome = "Daniela"
                        },
                        new
                        {
                            Id = 34,
                            Nome = "Rodrigo"
                        },
                        new
                        {
                            Id = 35,
                            Nome = "Leticia"
                        },
                        new
                        {
                            Id = 36,
                            Nome = "Sergio"
                        },
                        new
                        {
                            Id = 37,
                            Nome = "Bruna"
                        },
                        new
                        {
                            Id = 38,
                            Nome = "Caio"
                        },
                        new
                        {
                            Id = 39,
                            Nome = "Gabriela"
                        },
                        new
                        {
                            Id = 40,
                            Nome = "Samuel"
                        },
                        new
                        {
                            Id = 41,
                            Nome = "Isabela"
                        },
                        new
                        {
                            Id = 42,
                            Nome = "Lucas"
                        },
                        new
                        {
                            Id = 43,
                            Nome = "Natalia"
                        },
                        new
                        {
                            Id = 44,
                            Nome = "Paulo"
                        },
                        new
                        {
                            Id = 45,
                            Nome = "Bianca"
                        },
                        new
                        {
                            Id = 46,
                            Nome = "Matheus"
                        },
                        new
                        {
                            Id = 47,
                            Nome = "Renata"
                        },
                        new
                        {
                            Id = 48,
                            Nome = "Vitor"
                        },
                        new
                        {
                            Id = 49,
                            Nome = "Amanda"
                        },
                        new
                        {
                            Id = 50,
                            Nome = "Leandro"
                        });
                });

            modelBuilder.Entity("form_API.Models.Aluno", b =>
                {
                    b.HasOne("form_API.Models.Professor", "Professor")
                        .WithMany("Alunos")
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Professor");
                });

            modelBuilder.Entity("form_API.Models.Professor", b =>
                {
                    b.Navigation("Alunos");
                });
#pragma warning restore 612, 618
        }
    }
}
