name: Build and deploy Nuxt app to Azure Web App - SPA-Vue

on:
  push:
    branches:
      - master
    paths:
      - 'project_form/**'
      - '.github/workflows/master_spa-vue.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v5
        with:
          node-version: '22'
          cache: npm
          cache-dependency-path: project_form/package-lock.json

      - name: Install frontend dependencies
        run: npm ci
        working-directory: project_form

      - name: Run unit tests
        run: npm test
        working-directory: project_form

      - name: Generate static Nuxt app
        run: npm run generate
        working-directory: project_form

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: nuxt-static-app
          path: project_form/.output/public

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'workflow_dispatch'
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: nuxt-static-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_03FD0569EF9B480A8FDD84FCA537AB63 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D3F20EDB798A4F2B9FC3580E1AD521B3 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_13D06A19268E410B9E93CC11E38E7304 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'SPA-Vue'
          slot-name: 'Production'
          package: .
